### ISSUE TITLE
Severe TPS Impact in 1.10.2

### ISSUE THREAD

**Issue by Boolyman** [TheXFactor117/Levels#101]
Had to trouble shoot my modpack today, to find out exactly why my TPS was so low.  It was hovering around 2-3TPS instead of 20.  I went through every mod, removing and restarting to check the TPS.  Every mod performed perfectly, until I got to Levels.  When I removed it, the TPS went back to perfect.  So I installed it again just to confirm it wasn't a fluke.  Sure enough, jthe TPS dropped back down to single digits.  I had to remove your pack, which is a shame, because the server it was going to was looking forward to using your mod.

Levels 1.10.2-r1.2.4
Minecraft 1.10.2
forge: 12.18.3.2239

**Comment by TheXFactor117** [comment]
That is very strange...Levels is meant to be a lightweight mod, and I can't really think of anything off the top of my head that would cause the TPS to drop.

Does it just happen in general? With the mod installed, is the TPS always low or does it fluctuate? Did it happen just after you updated Levels?

**Comment by TheXFactor117** [comment]
I'm testing it right now and my TPS never dips below 20. I think I'll just need more information about it before I can really look into it and see if it's a problem.

**Comment by Boolyman** [comment]
Unfortunetly without it producing an error report, there isnt much I can provide as far as more information.     Guess there isnt much that can be done.

**Comment by TheXFactor117** [comment]
Hmm. I mean I don't know what would be causing it. Levels is meant to be lightweight.
