### ISSUE TITLE
Crash While Using Ender Dragon Bow from ArmorPlus

### ISSUE THREAD

**Issue by kenijey** [TheXFactor117/Levels#105]
[crash-2017-03-13_18.31.59-server.txt](https://github.com/TheXFactor117/Levels/files/838684/crash-2017-03-13_18.31.59-server.txt)
help please...
i just shot the Golem boss from battle towers mod with ender dragon bow from armorplus.

**Comment by TheXFactor117** [comment]
Backport to r1.2.6 for the time being.

**Comment by kenijey** [comment]
what? should i try with version r1.2.6 ?

**Comment by TheXFactor117** [comment]
Yes. r1.2.7 is broken.

**Comment by TheXFactor117** [comment]
See #104
