### ISSUE TITLE
Crashed When Press "L" With An Armor

### ISSUE THREAD

**Issue by kenijey** [TheXFactor117/Levels#106]
i get an armor which from Lost Eclipse mod, then pressed L and it crashed. here is the crash report...
[crash-2017-03-13_21.57.38-client.txt](https://github.com/TheXFactor117/Levels/files/839473/crash-2017-03-13_21.57.38-client.txt)

**Comment by TheXFactor117** [comment]
r1.2.7 is broken. Revert to r1.2.6.

**Comment by TheXFactor117** [comment]
See #104
