### ISSUE TITLE
Important Crash

### ISSUE THREAD

**Issue by kenijey** [TheXFactor117/Levels#107]
i just hit a mob with a diamond sword. it crashed. 
and the important thing is, i tried with other mods weapons, i couldn't hit ANY mob with any sword BUT my hand or a block / non attack damage item. please help.
[crash-2017-03-14_18.01.57-server.txt](https://github.com/TheXFactor117/Levels/files/841743/crash-2017-03-14_18.01.57-server.txt)

**Comment by TheXFactor117** [comment]
r1.2.7 is broken. Revert to r1.2.6.

**Comment by TheXFactor117** [comment]
See #104
