### ISSUE TITLE
Debug Printouts Spamming Console

### ISSUE THREAD

**Issue by Darkosto** [TheXFactor117/Levels#108]
Hello,

Is it possible to remove the debug printouts for your packet code in the console?

http://pastebin.com/16CrsfYT

MC: 1.10.2
Levels: r1.2.8
Forge: 2254

Thank you :)
Darkosto

**Comment by TheXFactor117** [comment]
I'll remove them. Must've forgot I put them in there.

**Comment by Darkosto** [comment]
I appreciate that! Thank you very much! :)
