### ISSUE TITLE
(1.10.2) Crash when hovering over armor with attributes already applied to it

### ISSUE THREAD

**Issue by Numba90** [TheXFactor117/Levels#109]
I had previously added the vanilla speed attribute to some boots, after installing version r1.2.8 (1.10.2) the game crashes when hovering over the item.
https://pastebin.com/4v83kGFb
I have not tested this in 1.11.

**Comment by TheXFactor117** [comment]
I am re-writing the mod right now to address the ability system. This bug will be fixed in the process.
