### ISSUE TITLE
Crash when adding tooltip for modded "mainhand" armor

### ISSUE THREAD

**Issue by Konlii** [TheXFactor117/Levels#114]
Levels crashes when adding tooltip to modded armor with EntityEquipmentSlot.MAINHAND armor type.

[crash-2017-04-23_15.18.41-client.txt](https://github.com/TheXFactor117/Levels/files/950001/crash-2017-04-23_15.18.41-client.txt)

**Comment by TheXFactor117** [comment]
I know what the issue is. I am actually in the process of writing Levels 3, which will actually fix this issue. I'll likely release a beta version of it later today. Levels 2 has a lot of issues with it, which Levels 3 attempts to fix. If the issue persists in Levels 3, you can reopen this issue.
