### ISSUE TITLE
Levels 3 beta issue

### ISSUE THREAD

**Issue by werff** [TheXFactor117/Levels#116]
First of all, I love your mod, it's a great job and I love using it!

Now, the problem...
For some reason the common weapon level reduces the base damage and speed of the weapons :/ it shouldn't do that, if you want to make a level worse than the base atributes of the tool cool (call it por or something like that).

Also the speed leveling is too fast, getting a 1.6 speed to 2,3 in rare, in 3 levels it's way too much (for pvp XD) could you add a little config option in order to tweak this kind of things?

Well, thanks for reading and I love you mod :D

**Comment by TheXFactor117** [comment]
This will be tweaked.
