### ISSUE TITLE
Levels 3 crashes with lost eclipse

### ISSUE THREAD

**Issue by kenijey** [TheXFactor117/Levels#117]
[crash-2017-04-26_14.48.35-client.txt](https://github.com/TheXFactor117/Levels/files/958245/crash-2017-04-26_14.48.35-client.txt)
[crash-2017-04-26_14.49.21-client.txt](https://github.com/TheXFactor117/Levels/files/958246/crash-2017-04-26_14.49.21-client.txt)
using forge 2284. thanks.

**Comment by TheXFactor117** [comment]
Use Levels 2 with Lost Eclipse.
