### ISSUE TITLE
Issue when running on server

### ISSUE THREAD

**Issue by linksith** [TheXFactor117/Levels#122]
Server kicks you for making a wooden axe...

Minecraft Version - 1.11.2 (for client AND server)
Forge version - 13.20.0.2298 (for client AND server)
Levels Version - 3.0.0-bet
Other Mods - [Minecraft, MCP, FML, Minecraft Forge, mercurius_updater]
Reports/Logs - https://pastebin.com/hGnnxmD6
How to reproduce -  install mod on server and client, join server, make a wooden axe *BOOM*

**Comment by Nachtflame** [comment]
Also having this issue in my server only (no problem at all on single player /LAN). But not limited to the wooden axe, but any sword/axe/armor set to get a rarity. 
 Get a "NPE:Ticking Player" that spams the server console, and player gets booted. Server continues running just fine.

**Comment by Nachtflame** [comment]
Just a note as well,  this seems to be the same issue as #119.

**Comment by TheXFactor117** [comment]
Looking into this.

**Comment by TheXFactor117** [comment]
So I booted up a server and made a wooden axe perfectly fine, so this should be fixed as well.
