### ISSUE TITLE
crash while fighting ender dragon

### ISSUE THREAD

**Issue by SDUBZ** [TheXFactor117/Levels#123]
[crash-2017-05-27_11.33.26-server.txt](https://github.com/TheXFactor117/Levels/files/1033268/crash-2017-05-27_11.33.26-server.txt)
[crash-2017-05-27_11.25.58-server.txt](https://github.com/TheXFactor117/Levels/files/1033269/crash-2017-05-27_11.25.58-server.txt)
Levels 3-1.11.2-3.0.0-beta
forge:1.11.2-2298

**Comment by TheXFactor117** [comment]
Looking into this.

**Comment by SDUBZ** [comment]
thanks mate :D

**Comment by TheXFactor117** [comment]
This issue should be fixed. I will do some more testing but for now I'll close this.
