### ISSUE TITLE
Crash when attacked by blue slime

### ISSUE THREAD

**Issue by lightlikeD** [TheXFactor117/Levels#127]
Version: 1.10.2
Forge: 12.18.3.2297
Levels-Version: 3.0.0-beta
Other mods: TConstruct 2.6.5

Reproduce: just getting attacked by a blue slime

Crash Report:

> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   FarseekCoreMod (Farseek-1.9.4-2.1.jar)
>   BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
>   LoadingPlugin (Quark-r1.1-70.jar)
>   MalisisCorePlugin (malisiscore-1.10.2-4.4.0.jar)
>   DynamicSurroundingsCore (DynamicSurroundings-1.10.2-3.4.5.1.jar)
>   ChiselCorePlugin (Chisel-MC1.10.2-0.0.10.22.jar)
>   CCLCorePlugin (CodeChickenLib-1.10.2-2.5.8.255-universal.jar)
>   FMLPlugin (InventoryTweaks-1.61-58.jar)
>   BlurPlugin (Blur-1.0.1-9.jar)
>   CoFH Loading Plugin (CoFHCore-1.10.2-4.1.1.156-universal.jar)
>   ForgelinPlugin (Forgelin-1.4.2.jar)
> Contact their authors BEFORE contacting forge
> 
> // Ouch. That hurt :(
> 
> Time: 6/1/17 6:33 PM
> Description: Ticking player
> 
> java.lang.NullPointerException: Ticking player
> 	at com.thexfactor117.levels.event.EventAttack.addExperience(EventAttack.java:133)
> 	at com.thexfactor117.levels.event.EventAttack.onLivingHurt(EventAttack.java:75)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_503_EventAttack_onLivingHurt_LivingHurtEvent.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
> 	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:504)
> 	at net.minecraft.entity.player.EntityPlayer.func_70665_d(EntityPlayer.java:1085)
> 	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:890)
> 	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1022)
> 	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:543)
> 	at net.minecraft.entity.monster.EntitySlime.func_175451_e(EntitySlime.java:249)
> 	at net.minecraft.entity.monster.EntitySlime.func_70100_b_(EntitySlime.java:241)
> 	at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:578)
> 	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:570)
> 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
> 	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233)
> 	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
> 	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
> 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213)
> 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
> 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
> 	at java.lang.Thread.run(Thread.java:745)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Server thread
> Stacktrace:
> 	at com.thexfactor117.levels.event.EventAttack.addExperience(EventAttack.java:133)
> 	at com.thexfactor117.levels.event.EventAttack.onLivingHurt(EventAttack.java:75)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_503_EventAttack_onLivingHurt_LivingHurtEvent.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
> 	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:504)
> 	at net.minecraft.entity.player.EntityPlayer.func_70665_d(EntityPlayer.java:1085)
> 	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:890)
> 	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1022)
> 	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:543)
> 	at net.minecraft.entity.monster.EntitySlime.func_175451_e(EntitySlime.java:249)
> 	at net.minecraft.entity.monster.EntitySlime.func_70100_b_(EntitySlime.java:241)
> 	at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:578)
> 	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:570)
> 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
> 	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233)
> 
> -- Player being ticked --
> Details:
> 	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
> 	Entity ID: 288
> 	Entity Name: lightlike
> 	Entity's Exact location: -418.88, 64.00, 350.05
> 	Entity's Block location: World: (-419,64,350), Chunk: (at 13,4,14 in -27,21; contains blocks -432,0,336 to -417,255,351), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
> 	Entity's Momentum: 0.07, -0.08, 0.00
> 	Entity's Passengers: []
> 	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
> Stacktrace:
> 	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
> 	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
> 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213)
> 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
> 
> -- Ticking connection --
> Details:
> 	Connection: net.minecraft.network.NetworkManager@1a292153
> Stacktrace:
> 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
> 	at java.lang.Thread.run(Thread.java:745)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.10.2
> 	Operating System: Windows 7 (amd64) version 6.1
> 	Java Version: 1.8.0_25, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 1665089960 bytes (1587 MB) / 3996123136 bytes (3811 MB) up to 4772593664 bytes (4551 MB)
> 	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5120m -Xms256m -XX:PermSize=256m
> 	IntCache: cache: 2, tcache: 0, allocated: 9, tallocated: 61
> 	FML: MCP 9.32 Powered by Forge 12.18.3.2297 Optifine OptiFine_1.10.2_HD_U_D8 88 mods loaded, 88 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
> 	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2297.jar) 
> 	UCHIJAAAA	Forge{12.18.3.2297} [Minecraft Forge] (forge-1.10.2-12.18.3.2297.jar) 
> 	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
> 	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.8.255-universal.jar) 
> 	UCHIJAAAA	Baubles{1.3.11} [Baubles] (Baubles-1.10.2-1.3.11.jar) 
> 	UCHIJAAAA	Botania{r1.9-341} [Botania] (Botania r1.9-341.jar) 
> 	UCHIJAAAA	AkashicTome{1.0-5} [Akashic Tome] (AkashicTome-1.0-5.jar) 
> 	UCHIJAAAA	JEI{3.14.7.419} [Just Enough Items] (jei_1.10.2-3.14.7.419.jar) 
> 	UCHIJAAAA	cofhcore{4.1.1} [CoFH Core] (CoFHCore-1.10.2-4.1.1.156-universal.jar) 
> 	UCHIJAAAA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.4.1.jar) 
> 	UCHIJAAAA	flyringbaublemod{0.2.4_1.10.2-d71eb9e} [AngelRing 2 Bauble] (angelRingToBauble-1.10.2-0.2.4.19+d71eb9e.jar) 
> 	UCHIJAAAA	Morphtool{1.0-12} [Morph-o-Tool] (Morph-o-Tool-1.0-12.jar) 
> 	UCHIJAAAA	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
> 	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
> 	UCHIJAAAA	ichunutil{6.3.2} [iChunUtil] (iChunUtil-1.10.2-6.3.2.jar) 
> 	UCHIJAAAA	backtools{6.2.0} [BackTools] (BackTools-1.10.2-6.0.0.jar) 
> 	UCHIJAAAA	BBG{5.0.0} [BetterBedrockGen] (BBG-1.9.4-5.0.0.jar) 
> 	UCHIJAAAA	BetterAchievements{0.3.3.10} [Better Achievements] (BetterAchievements-1.10.2-0.3.3.10.jar) 
> 	UCHIJAAAA	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.10.2-0.11.1.220+f8232fe.jar) 
> 	UCHIJAAAA	BiomesOPlenty{5.0.0.2236} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2236-universal.jar) 
> 	UCHIJAAAA	blockdrops{1.1.1} [Block Drops] (BlockDrops-1.10.2-1.1.1.jar) 
> 	UCHIJAAAA	blur{1.0.1-9} [Blur] (Blur-1.0.1-9.jar) 
> 	UCHIJAAAA	bookshelf{1.4.4.347} [Bookshelf] (Bookshelf-1.10.2-1.4.4.347.jar) 
> 	UCHIJAAAA	Chameleon{1.10.2-2.3.0} [Chameleon] (Chameleon-1.10.2-2.3.0.jar) 
> 	UCHIJAAAA	chisel{MC1.10.2-0.0.10.22} [Chisel] (Chisel-MC1.10.2-0.0.10.22.jar) 
> 	UCHIJAAAA	CodeChickenLib{2.5.8.255} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.8.255-universal.jar) 
> 	UCHIJAAAA	cosmeticarmorreworked{1.10.2-v2a} [CosmeticArmorReworked] (CosmeticArmorReworked-1.10.2-v2a.jar) 
> 	UCHIJAAAA	cyberware{beta-0.2.10} [Cyberware] (cyberware-1.9.4-1.10.2-beta-0.2.10.jar) 
> 	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
> 	UCHIJAAAA	darkutils{1.1.8.finalrc1} [Dark Utilities] (DarkUtilities-1.1.8.finalrc1.jar) 
> 	UCHIJAAAA	DurabilityShow{3.1.1} [Durability Show] (Durability Show-1.9.4-3.1.1.jar) 
> 	UCHIJAAAA	dsurround{3.4.5.1} [§3Dynamic Surroundings] (DynamicSurroundings-1.10.2-3.4.5.1.jar) 
> 	UCHIJAAAA	presets{3.4.5.1} [§3Presets!] (DynamicSurroundings-1.10.2-3.4.5.1.jar) 
> 	UCHIJAAAA	farseek{2.1} [Farseek] (Farseek-1.9.4-2.1.jar) 
> 	UCHIJAAAA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
> 	UCHIJAAAA	forestry{5.2.17.376} [Forestry] (forestry_1.10.2-5.2.17.376.jar) 
> 	UCHIJAAAA	forgelin{1.4.2} [Forgelin] (Forgelin-1.4.2.jar) 
> 	UCHIJAAAA	friendlyfire{1.3.0} [Friendly Fire] (FriendlyFire-1.10.2-1.3.0.jar) 
> 	UCHIJAAAA	mcmultipart{1.4.0} [MCMultiPart] (MCMultiPart-1.4.0-universal.jar) 
> 	UCHIJAAAA	ftbl{0.0.0} [FTBLib] (FTBLib-1.1x-3.6.5.jar) 
> 	UCHIJAAAA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.1x-3.6.5.jar) 
> 	UCHIJAAAA	fw{1.5.0} [Fullscreen Windowed] (FullscreenWindowed-1.10.2-1.5.0.jar) 
> 	UCHIJAAAA	gravestone{1.5.12} [Gravestone] (GraveStone Mod 1.5.12.jar) 
> 	UCHIJAAAA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
> 	UCHIJAAAA	tconstruct{1.10.2-2.6.5.10} [Tinkers' Construct] (TConstruct-1.10.2-2.6.5.jar) 
> 	UCHIJAAAA	immersiveengineering{0.10-58} [Immersive Engineering] (ImmersiveEngineering-0.10-58.jar) 
> 	UCHIJAAAA	immersivepetroleum{1.0.4} [Immersive Petroleum] (immersivepetroleum-1.10.2-1.0.4.jar) 
> 	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
> 	UCHIJAAAA	ironbackpacks{1.10.2-2.2.26} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.26.jar) 
> 	UCHIJAAAA	ironchest{1.10.2-7.0.15.804} [Iron Chest] (ironchest-1.10.2-7.0.15.804.jar) 
> 	UCHIJAAAA	JEFB{1.0.4} [Just Enough Forestry Bees] (jefb_1.10.2-1.0.4.jar) 
> 	UCHIJAAAA	journeymap{1.10.2-5.4.6} [JourneyMap] (journeymap-1.10.2-5.4.6.jar) 
> 	UCHIJAAAA	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
> 	UCHIJAAAA	KaishiWeapons{v0.1} [Kaishi's Weapons Pack] (KaishiWeapons-1.9.4.jar) 
> 	UCHIJAAAA	levels{3.0.0} [Levels 3] (Levels 3-1.10.2-3.0.0-beta.jar) 
> 	UCHIJAAAA	llor{1.1.1-mc[1.9-1.11]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.1-mc[1.9-1.11].jar) 
> 	UCHIJAAAA	malisiscore{1.10.2-4.4.0} [MalisisCore] (malisiscore-1.10.2-4.4.0.jar) 
> 	UCHIJAAAA	malisisdoors{1.10.2-5.2.0} [MalisisDoors] (malisisdoors-1.10.2-5.2.0.jar) 
> 	UCHIJAAAA	testdummy{1.11} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.10.2-1.13.jar) 
> 	UCHIJAAAA	StorageDrawers{1.10.2-3.7.7} [Storage Drawers] (StorageDrawers-1.10.2-3.7.7.jar) 
> 	UCHIJAAAA	refinedstorage{1.2.25} [Refined Storage] (refinedstorage-1.2.25.jar) 
> 	UCHIJAAAA	moartinkers{0.4.1} [Moar Tinkers] (moartinkers-0.4.1.jar) 
> 	UCHIJAAAA	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.10.2.jar) 
> 	UCHIJAAAA	natura{1.10.2-4.1.0.65} [Natura] (natura-1.10.2-4.1.0.65.jar) 
> 	UCHIJAAAA	Neat{1.3-12} [Neat] (Neat 1.3-12.jar) 
> 	UCHIJAAAA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
> 	UCHIJAAAA	passthroughsigns{2.0.1} [Passthrough Signs] (PassthroughSigns-1.10.2-2.0.1.jar) 
> 	UCHIJAAAA	railcraft{10.1.2} [Railcraft] (Railcraft_1.10.2-10.1.2.jar) 
> 	UCHIJAAAA	rccosmetic{3.0.5} [Railcraft Cosmetic Additions] (RailCraft Cosmetic Additions-3.0.5.jar) 
> 	UCHIJAAAA	realdrops{1.0.9} [Realistic Item Drops] (RealisticItemDrops-1.0.9.jar) 
> 	UCHIJAAAA	ropebridge{2.0.5} [Rope Bridge] (ropebridge-1.10.2-2.0.5.jar) 
> 	UCHIJAAAA	RTG{4.2.0.0-snapshot-1} [Realistic Terrain Generation] (RTG-1.10.2-4.2.0.0-snapshot-1.jar) 
> 	UCHIJAAAA	shadowmc{3.6.1} [ShadowMC] (ShadowMC-1.10.2-3.6.1.jar) 
> 	UCHIJAAAA	SleepingBag{1.4.0} [Sleeping Bag] (SleepingBag-1.10.2-1.4.0.jar) 
> 	UCHIJAAAA	SophisticatedWolves{3.6.1} [SophisticatedWolves] (SophisticatedWolves-3.6.5.jar) 
> 	UCHIJAAAA	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.9.4.jar) 
> 	UCHIJAAAA	stg{1.0.2} [SwingThroughGrass] (stg-1.0.2.jar) 
> 	UCHIJAAAA	streams{0.3} [Streams] (Streams-1.9.4-0.3.jar) 
> 	UCHIJAAAA	rscircuits{1.0.4} [Super Circuit Maker] (SuperCircuitMaker-1.0.4.jar) 
> 	UCHIJAAAA	terracart{1.10.2-2.1} [TerraCart] (terracart-1.10.2-2.1.jar) 
> 	UCHIJAAAA	thermalfoundation{2.0.5} [Thermal Foundation] (ThermalFoundation-1.10.2-2.0.5.81-universal.jar) 
> 	UCHIJAAAA	thermalexpansion{5.0.4} [Thermal Expansion] (ThermalExpansion-1.10.2-5.0.4.90-universal.jar) 
> 	UCHIJAAAA	tumbleweed{1.10-0.3.1} [Tumbleweed] (tumbleweed-1.10-0.3.1.jar) 
> 	UCHIJAAAA	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
> 	UCHIJAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.2.215.jar) 
> 	UCHIJAAAA	wawla{2.3.2.215} [What Are We Looking At] (Wawla-1.10.2-2.3.2.215.jar) 
> 	UCHIJAAAA	wired{1.7.0} [WIRED: More Augs] (WIRED-1.7.0.jar) 
> 	Loaded coremods (and transformers): 
> FarseekCoreMod (Farseek-1.9.4-2.1.jar)
>   farseek.core.FarseekClassTransformer
> BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
>   net.darkhax.bookshelf.asm.BookshelfTransformerManager
> LoadingPlugin (Quark-r1.1-70.jar)
>   vazkii.quark.base.asm.ClassTransformer
> MalisisCorePlugin (malisiscore-1.10.2-4.4.0.jar)
>   net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
>   net.malisis.core.util.chunkblock.ChunkBlockTransformer
>   net.malisis.core.renderer.transformer.MalisisRendererTransformer
>   net.malisis.core.renderer.icon.asm.TextureMapTransformer
>   net.malisis.core.util.clientnotif.ClientNotifTransformer
> DynamicSurroundingsCore (DynamicSurroundings-1.10.2-3.4.5.1.jar)
>   org.blockartistry.DynSurround.asm.Transformer
> ChiselCorePlugin (Chisel-MC1.10.2-0.0.10.22.jar)
>   team.chisel.common.asm.ChiselTransformer
> CCLCorePlugin (CodeChickenLib-1.10.2-2.5.8.255-universal.jar)
>   codechicken.lib.asm.ClassHeirachyManager
>   codechicken.lib.asm.CCL_ASMTransformer
> FMLPlugin (InventoryTweaks-1.61-58.jar)
>   invtweaks.forge.asm.ContainerTransformer
> BlurPlugin (Blur-1.0.1-9.jar)
>   com.tterrag.blur.BlurTransformer
> CoFH Loading Plugin (CoFHCore-1.10.2-4.1.1.156-universal.jar)
>   cofh.asm.CoFHClassTransformer
>   cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
> ForgelinPlugin (Forgelin-1.4.2.jar)
> 
>   
> 	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
> 	Pulsar/tconstruct loaded Pulses: 
> 		- TinkerCommons (Enabled/Forced)
> 		- TinkerWorld (Enabled/Not Forced)
> 		- TinkerTools (Enabled/Not Forced)
> 		- TinkerHarvestTools (Enabled/Forced)
> 		- TinkerMeleeWeapons (Enabled/Forced)
> 		- TinkerRangedWeapons (Enabled/Forced)
> 		- TinkerModifiers (Enabled/Forced)
> 		- TinkerSmeltery (Enabled/Not Forced)
> 		- TinkerGadgets (Enabled/Not Forced)
> 		- TinkerOredict (Enabled/Forced)
> 		- TinkerIntegration (Enabled/Forced)
> 		- TinkerFluids (Enabled/Forced)
> 		- TinkerMaterials (Enabled/Forced)
> 		- TinkerModelRegister (Enabled/Forced)
> 		- WailaIntegration (Enabled/Not Forced)
> 
> 	Pulsar/natura loaded Pulses: 
> 		- NaturaCommons (Enabled/Forced)
> 		- NaturaOverworld (Enabled/Not Forced)
> 		- NaturaNether (Enabled/Not Forced)
> 		- NaturaDecorative (Enabled/Not Forced)
> 		- NaturaTools (Enabled/Not Forced)
> 		- NaturaEntities (Enabled/Not Forced)
> 		- NaturaOredict (Enabled/Forced)
> 		- NaturaWorld (Enabled/Not Forced)
> 		- WailaIntegration (Enabled/Not Forced)
> 
> 	CodeChickenLib Invalid Fingerprint Reports: 
> 	Profiler Position: N/A (disabled)
> 	Player Count: 1 / 8; [EntityPlayerMP['lightlike'/288, l='Railworld', x=-418.88, y=64.00, z=350.05]]
> 	Type: Integrated Server (map_client.txt)
> 	Is Modded: Definitely; Client brand changed to 'fml,forge'
> 	OptiFine Version: OptiFine_1.10.2_HD_U_D8
> 	Render Distance Chunks: 8
> 	Mipmaps: 4
> 	Anisotropic Filtering: 1
> 	Antialiasing: 0
> 	Multitexture: false
> 	Shaders: null
> 	OpenGlVersion: 4.5.13474 Compatibility Profile Context 22.19.157.3
> 	OpenGlRenderer: AMD Radeon (TM) R9 390 Series
> 	OpenGlVendor: ATI Technologies Inc.
> 	CpuCount: 8

**Comment by TheXFactor117** [comment]
Looking into this.

**Comment by TheXFactor117** [comment]
This should be fixed. Will do some more testing, but for now closing this.
