### ISSUE TITLE
[1.11.2][Levels 3] Client call on server side (again)

### ISSUE THREAD

**Issue by Terpo** [TheXFactor117/Levels#128]
This is a reminder to https://github.com/TheXFactor117/Levels/issues/119
Just a new Client call on server side ^^

https://gist.githubusercontent.com/Terpo/a820b1a6c81ec3f2c463d11141836a7b/raw/4ef5c9f1e73afabee323afb94640e87941d9ec2f/gistfile1.txt

Its stilll a server <-> client problem where the client gets kicked from the game. 

Search for:

```Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$PlayerTickEvent@327c4918:
java.lang.NoSuchMethodError: net.minecraft.item.ItemArmor.func_185083_B_()Lnet/minecraft/inventory/EntityEquipmentSlot;
at com.thexfactor117.levels.util.WeaponHelper.setAttributeModifiers(WeaponHelper.java:107) ~[WeaponHelper.class:?]
at com.thexfactor117.levels.util.WeaponHelper.create(WeaponHelper.java:67) ~[WeaponHelper.class:?]
at com.thexfactor117.levels.event.EventCreateWeapon.create(EventCreateWeapon.java:62) ~[EventCreateWeapon.class:?]
at com.thexfactor117.levels.event.EventCreateWeapon.onPlayerTick(EventCreateWeapon.java:37) ~[EventCreateWeapon.class:?]
```

```
    @SideOnly(Side.CLIENT)
    public EntityEquipmentSlot getEquipmentSlot()
    {
        return this.armorType;
    }
```

**Comment by TheXFactor117** [comment]
I haven't released the new build. This issue should be fixed when I get a chance to release it.

**Comment by Terpo** [comment]
oh, a random server crash appears https://github.com/TheXFactor117/Levels/issues/129 :)

And as I wrote above, it is a new bug. I know that you fixed the other one. I tested this bug from a build direclty from the latest source code, not 3.0.0. Sry that I forgot to add that part.

**Comment by TheXFactor117** [comment]
Oh ok, I see now. I'll fix this today or tomorrow.
