### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by JVanhook** [TheXFactor117/Levels#129]
In Beta 3.0.1 on my server i still experience the tick crash with armor and then im hit with an io exception and have to delete player data to login again

**Comment by Terpo** [comment]
I referenced my old issue with all information to close that bug with the armors.

**Comment by JVanhook** [comment]
Not sure if it makes a difference but I was running Minecraft​ 1.10.2 at the time

**Comment by TheXFactor117** [comment]
Is the issue on 1.10.2 or 1.11.2 or both? Can I have the new crash reports as well.

**Comment by TheXFactor117** [comment]
This has been fixed now. Will release a build with this fix in a second.

**Comment by JVanhook** [comment]
i see you fixed the issue i only discovered this on 1.10.2 and heres the log
[crash-2017-06-07_03.34.41-server.txt](https://github.com/TheXFactor117/Levels/files/1061971/crash-2017-06-07_03.34.41-server.txt)
