### ISSUE TITLE
[1.10.2] [Levels 3] Ticking entity issues

### ISSUE THREAD

**Issue by 115kino** [TheXFactor117/Levels#130]
Name: Levels 3
Version 3.0.0
Jar Version: Levels 3-1.10.2-3.0.0-beta
Crash Report: https://pastebin.com/BMALWRVj

A user reported about this a bit ago about an issue with getting hit by a Slider. This is similar in regards to issue #100 however the issue causing the crash is different. I cannot clearly identify where the issue is since i've just been pointed to blank lines.

**Comment by TheXFactor117** [comment]
This issue should be fixed in 3.0.1-beta which has just been released.
