### ISSUE TITLE
[1.9.4] Offhand Doesn't Level/Procs mainhand effects

### ISSUE THREAD

**Issue by Alaberti** [TheXFactor117/Levels#22]
Not sure if intentional or not). Tested with 2 diamond swords (both rare).

**Comment by TheXFactor117** [comment]
Hmm I know why this isn't working - I'll look into a fix for it. Alongside that I'll probably also be looking to further integrating both the new 1.9 features and Levels more.

**Comment by TheXFactor117** [comment]
I'm closing this for now because I can't seem to find an issue with it. Just comment if something is still wrong.

**Comment by Alaberti** [comment]
The problem is occurs with the better combat mod, which allows you to swing with each arm. I'll also report with them, but I think that's the missing link between my report and your findings.
