### ISSUE TITLE
Durability Config Is Ignored

### ISSUE THREAD

**Issue by SilentChaos512** [TheXFactor117/Levels#23]
Playing on a server and the durability config seems to be ignored. I set the enable durability config to 'true' on the server and weapons and some types of armor still take no damage. For weapons, I can confirm this happens with swords from vanilla, Silent's Gems, and Ebon Arts at least. The armor that seems broken is a new type from Gems, so it could be I've done something wrong, but it takes damage in my development environment, which does not have Levels installed.

**Comment by ruyanve** [comment]
Not confirmed!
Using Forge 1968
Levels: 3.0.3

Weapons show durability: unilimited, but they work as intended.

**Comment by TheXFactor117** [comment]
Hmm, I know there are issues with durability to begin with, particularly with armor. Durability support for armor hasn't fully been implemented yet.

As with weapons, durability should work fine, even with the tooltip, but obviously that's not the case. I'll look into it now, and will push a release when I get it working.

**Comment by TheXFactor117** [comment]
Will be fixed in r3.0.5

**Comment by SilentChaos512** [comment]
Still broken in r3.0.9. Regardless of the damage on an item beforehand, their damage value is set to 1 whenever weapons are used to attack or armor is damaged. Tried on singleplayer and server this time, double checking that 'enableDurability' was set to true on both the client and server.

**Comment by TheXFactor117** [comment]
Maybe I'm not understanding exactly what is wrong - I'm still not able to reproduce durability not working.

![screen shot 2016-06-28 at 10 43 56 am](https://cloud.githubusercontent.com/assets/6678711/16420011/b64a3e42-3d1d-11e6-936c-1ff389d8c790.png)

Swords are taking durability (and updating bar if you look closely), and armor is also taking durability (bar being visible).

**Comment by SilentChaos512** [comment]
Oh, the config file was moved into its own folder, I didn't realize. Sorry for wasting your time!

Great mod by the way, I love how it's compatible with mine. Keep up the great work!

**Comment by TheXFactor117** [comment]
Glad you've seemed to get everything sorted out.

And thanks, I appreciate it!
