### ISSUE TITLE
Dragon suicide bug?

### ISSUE THREAD

**Issue by LimeTheOn** [TheXFactor117/Levels#26]
Levels r 309
forge 1987
MP
Dragon insta-dies to armor with Levels on it.
Tested with: Vanilla, Bloodmagic, ArmorPlus

**Comment by TheXFactor117** [comment]
The only way the dragon will die is if you have the Void ability on your armor. If you do have that ability, I can see why that happens - I probably can definitely look into fixing that if it is indeed the problem.

If you don't have Void on your armor, I doubt that's an issue with Levels - though testing in an Levels only instance would probably help determine that.

**Comment by undead09** [comment]
I am the one who tested it for/with him it happens with diamond armor with frozen enchant for sure and void for sure and it happened with a armor set with frozen and molten, we spent about 2 hours making sure it was levels only however it seemed more common when i used blood magic sentient bow but it also happened without it so it is definitively levels.

**Comment by LimeTheOn** [comment]
Yeah just for clarification, it should not work on the Dragon,Wither, or even the Elder Guardians (any type of boss mobs basically). Thats my opinion tho so feel free to do whatever you feel balanced.

**Comment by TheXFactor117** [comment]
The way Void handles killing the entity is simple just by setting the health to zero (in order for it to drop loot), however, I can see about adjusting it to set the health to say 0.5 points? This way, it's basically a one hit kill after that, which should fix up these issues.

**Comment by LimeTheOn** [comment]
Alright I see your point and i would accept but i cant. Let me evaluate on the matter a bit more. We got an EnderDragon which is hard to kill, drops some endgame gear, guards endgame resources and a whole dimension supposedly THE Boss of the game.Just to put numbers behind my argument here on our server its even infernal to add to this Endgame boss feel and we got her HP doubled currently. That means minimum 400HP add infernal buffs and you can see the player should be facing one hell of a fight...but. Even with your presented change that would mean minus 399.5 HP loss in 1 second then one hit and gone...spawn another one...continue until you're filthy rich, swimming in XP. I see Void as a very cool enhancement and I believe a blacklist of mobs in the configs could fix the problem and would make it a more attractive mod of choice for authors like me who like to customize what they can and sadly when Its breaking even vanilla game logic not just mine I have to remove it.

**Comment by TheXFactor117** [comment]
You have to take into consideration that it doesn't happen every time. There's only a 5% chance it will  happen, which isn't that much at all. I might just consider adding a blacklist of mobs that this will effect, excluding the Ender Dragon for example. Other than that, changing the ability likely won't happen.

**Comment by TheXFactor117** [comment]
Closing this. r4.1.0+ added features to bypass this error.
