### ISSUE TITLE
Armor looses durability despite config file durability disabled

### ISSUE THREAD

**Issue by sparkocm** [TheXFactor117/Levels#29]
Hi, 

I am running a server with some friends and we are using Levels r3.0.1 with Forge 10.13.4.1614. 

We noticed that the armors (vanilla and mods like: botania, magical crops and metallurgy) are loosing durability despite our config file having durability disabled. 

I am linking a pastebin copy of the config file we are using on the server. Please let know what other information I can facilitate you. 

[http://pastebin.com/0348kmez](url)

**Comment by TheXFactor117** [comment]
Hmm, if I remember, armor didn't have support for enabled durability in that version - but maybe I'm wrong. Either way, 1.7.10 is outdated, and I don't have any plans to support it anymore unfortunately. My only advice would be to update.
