### ISSUE TITLE
[Crash] Crash when hitting test Dummy

### ISSUE THREAD

**Issue by nikkimas** [TheXFactor117/Levels#30]
When I hit the test Dummy of the mod "MmmMmmMmmMmm" (yes thats the name...) the game crashes. [http://pastebin.com/Ew84q8Ny](http://pastebin.com/Ew84q8Ny). I'm not 100% sure if it's Levels causing the crash. If it's not, I'm sorry.

**Comment by TheXFactor117** [comment]
Can you reproduce it? Does it happen just hitting a test dummy with any sword?

**Comment by TheXFactor117** [comment]
Should be fixed in r4.1.3
