### ISSUE TITLE
[1.10.2] Build error

### ISSUE THREAD

**Issue by NemoChenTW** [TheXFactor117/Levels#33]
Hi, I got building problem when I use "gradlew build".

I found out the building dependencies of "libs/Waila-1.7.0-B3_1.9.4-dev.jar".
After I download this jar form internet and put it to the right location, **building success**.

I don't know the error occurred because of my environment error or the 990eb3e missed some setting.

**Comment by TheXFactor117** [comment]
I removed the libs folder because I didn't want to host that file in this repo. I just need to add a note that WAILA is required to build the mod in the first place if I haven't already.
