### ISSUE TITLE
Levels glitches with Better Combat

### ISSUE THREAD

**Issue by Math321** [TheXFactor117/Levels#35]
(One of Better Combat's main features is that you can hold weapons in either hand and have them both work.)

If I hold a sword with Ancient rarity in the main hand, and another weapon in my off hand, the off hand weapon acts like it has Ancient's 3x damage feature, along with any Levels abilities the main hand weapon has, even though it isn't an Ancient weapon. (This can even allow weapons that can't usually have Levels abilities to act like they do, which is...strange, and a bit broken. Vanilla axes, Tinker's Construct weapons, anything, really.)

If Levels' config is changed so that weapons have durability, high-rarity weapons in the offhand don't appear to randomly regain durability during use, even though they're supposed to.

**Comment by TheXFactor117** [comment]
The issue is how the offhand is handled. I might be able to do something, but I would need to see how Better Combat makes it's feature work properly first. I'm re-writing the mod right now and will see about fixing it.

**Comment by TheXFactor117** [comment]
Let me know if the issue still persists in the new version of Levels releasing shortly.
