### ISSUE TITLE
Lag happended When maxLevelCap set A HUGE NUMBER

### ISSUE THREAD

**Issue by Nathan8489** [TheXFactor117/Levels#37]
If someone try to set maxLevelCap to a number like 99999 to get a infinite max level.

Lag happended when a weapon or armor level up each time.

Can you solve it?

**Comment by TheXFactor117** [comment]
I'll need more details than that. When I finish Levels 2, a level cap of something like 100 would be close to infinite simply because the amount of experience need would exponentially increase.
