### ISSUE TITLE
[Suggestion] Config option to add and remove items

### ISSUE THREAD

**Issue by ulkunderscore** [TheXFactor117/Levels#38]
I am using the [Sleeping Bag](https://minecraft.curseforge.com/projects/sleeping-bag) mod and it is treated as armor by Levels because it's equippable to sleep through the night. 
There are probably more items out there that only look like armor or a weapon in the code, or vice versa look like a tool.

**Comment by TheXFactor117** [comment]
I'll look into adding such a feature. Thanks for the suggestion!

**Comment by TheXFactor117** [comment]
Implemented. Will be in the upcoming beta for 1.11.
