### ISSUE TITLE
SSP Crash Fighting Mobs

### ISSUE THREAD

**Issue by Silvrus** [TheXFactor117/Levels#39]
Getting a crash when my iron armor tries to level during combat: http://pastebin.com/wcTZ4AKF 

Could be related to issue #36.

**Comment by TheXFactor117** [comment]
I'll look into it when I get a chance. I'll fix it when re-writing this portion of the mod.

**Comment by TheXFactor117** [comment]
Might be fixed in the new version of the mod, releasing shortly for 1.11.

**Comment by Silvrus** [comment]
Great, thanks for looking into this. Will this release for 1.10.2 as well?

**Comment by TheXFactor117** [comment]
It might work regardless. Throw it in a 1.10.2 environment and see what happens. If it doesn't work, I might release a version for 1.10.2. Two versions is hard to maintain, but I don't think there are big changes between the code.
