### ISSUE TITLE
[1.10.2] [Levels r4.1.3] [Immersive Engineering 0.10-47] Nullpointer on Ability Selection with IE Railgun

### ISSUE THREAD

**Issue by Alaberti** [TheXFactor117/Levels#40]
Seems Levels and the IE railgun don't get along very well.

http://pastebin.com/WP4HXaRf

**Comment by Alaberti** [comment]
@Blusunrize Sorry to summon you from the ether, do you have any super-secret defense against the dark arts insight on this?

**Comment by BluSunrize** [comment]
As far as I am aware this issue should lie on Levels side? But given that this is closed source? No idea. Would be great if the dev could say something on this? =P

**Comment by Alaberti** [comment]
It would lol looks like it broke at https://github.com/TheXFactor117/Levels/blob/1.10.2/src/main/java/com/thexfactor117/levels/leveling/AbilitySelection.java at 37 when there was nothing catching it; I imagine the railgun had null for level or something and there's nothing there to catch the error.

**Comment by Alaberti** [comment]
Ah ha, https://github.com/TheXFactor117/Levels/blob/1.10.2/src/main/java/com/thexfactor117/levels/events/EventLivingDeath.java line 124 - this is where it gets the xp prior to leveling the weapon which is when the ability selection comes into play. @BluSunrize Are railgun projectiles an instanceof EntityArrow? I'm going to assume you do your own thing?

**Comment by BluSunrize** [comment]
Nope. They extend arrows because projectiles don't sync properly otherwise

**Comment by Alaberti** [comment]
Not a problem, just trying to get to the bottom of it myself if need be lol but @TheXFactor117 would have invaluable insight

**Comment by TheXFactor117** [comment]
Sorry about not responding more quickly. I'd imagine this is something pretty easy to fix. So I'm assuming Levels is trying to add its systems onto the railgun right? And when the railgun is used, stuff doesn't work properly?

@BluSunrize Does the railgun extend ItemBow or no? This system might not work properly if it isn't.

Regardless, I'm in the process of redesigning the entire mod. I've got a list of issues I need to fix when I get around to rewriting the mod, so there is nothing I will be able to do about it now in terms of like a hotfix.

**Comment by Alaberti** [comment]
@TheXFactor117 That sums it up in a nutshell from what I can see. It seems like the problem only happens on a last-hit.

**Comment by BluSunrize** [comment]
@TheXFactor117 I absolutely blanked on replying to this, I apologize!
No, the Railgun does not extend Bow, but the projectile extends Arrows because otherwise they'd desync.

**Comment by TheXFactor117** [comment]
Issue might be fixed in upcoming beta for 1.11. Not sure though. The code causing the issue was removed entirely in the new version of the mod, however, the issue might still persist elsewhere.
