### ISSUE TITLE
Crash when killing mobs with TiCon shuriken

### ISSUE THREAD

**Issue by thetaCriterion** [TheXFactor117/Levels#41]
Crash log: http://pastebin.com/ug0qwCgt

Crash happens whenever the killing blow is dealt with the shuriken. Other TiCon weapons do not cause this crash.

**Comment by Moonlightneo** [comment]
Getting this with a TiCon, bow myself
http://pastebin.com/1BE8aB2w

**Comment by TheXFactor117** [comment]
TiCon seems to be pretty buggy with Levels. I'll look into improving the compatibility when re-writing the mod.

**Comment by TheXFactor117** [comment]
Should be fixed alongside #48 and #49 theoretically. Open a new issue if the crash persists using the new version of the mod which will be released soon.
