### ISSUE TITLE
Toxic, molten and other armor enchants hurting player.

### ISSUE THREAD

**Issue by PixelOaksHector** [TheXFactor117/Levels#42]
When a piece of armor receives one of the damage dealing effects when leveled it immediately starts affecting the player. Ver 1.10.2-r4.1.3

**Comment by TheXFactor117** [comment]
Could possibly be a bug. I'll look into it when re-writing that portion of the mod. Thanks!

**Comment by TheXFactor117** [comment]
Should be fixed in 1.11.2-b2.0.0
