### ISSUE TITLE
Issue with Simply Jetpacks 2

### ISSUE THREAD

**Issue by vtgamer** [TheXFactor117/Levels#43]
Hello,

I ran into an issue with Simply Jetpacks 2 (v2.0.3.14) where anytime I got hit by a mob the jetpacks would turn into a creative jetpack. However after removing Levels this no longer happened.

This is a custom pack I'm using in single player and attached is the profile export from curse in case you wanted to see what other mods I'm using.

Thanks,

VT

[VT Custom 1.1.zip](https://github.com/TheXFactor117/Levels/files/614089/VT.Custom.1.1.zip)

**Comment by TheXFactor117** [comment]
Hmm, this seems kind of strange but I will look into it when I get a chance.

**Comment by TheXFactor117** [comment]
I added a way to remove items like this from the leveling system in the upcoming beta for Levels.
