### ISSUE TITLE
No decay on weapons after enabled.

### ISSUE THREAD

**Issue by Avatarfreak345** [TheXFactor117/Levels#44]
After enabling weapon decay (Which in my opinion should always be enabled and then have the option to disable) Weapons fail to decay. It makes the weapons on a survival server OP'd.

**Comment by TheXFactor117** [comment]
I'm re-writing a new version of the mod right now and will have durability enabled all the time with the option to disable.

**Comment by TheXFactor117** [comment]
Durability will be fixed in the new version of the mod, which will be released soon.

**Comment by Avatarfreak345** [comment]
OK that is great news.
