### ISSUE TITLE
Void ability deletes player's inventory.

### ISSUE THREAD

**Issue by wiloxe** [TheXFactor117/Levels#46]
So when playing with friends we got ourself some awesome armor that was legendary -> Ancient.
And as you know Void is pretty easy sometimes to get on those kinds of armor...
So one of my friends was hitting me just for fun (We do that a lot) and then suddenly died only leaving XP no death message and no items at all. (The inventory was full btw) and this have happen many of times.
We are not sure what causes this issue. There's another issue from another mod that does same thing (Deletes inventory on death) and that's Glass Dagger from Blood Arsenal. No other reports of loosing inventory other than those two thing on the server. The glass dagger can be avoided but not the void ability.
Mod/Minecraft/Forge Versions:
Minecraft: 1.10.2
Forge: 12.18.2151
Levels: 1.10.2-r4.1.3
If any other information is required feel free to ask.
(Also i am not 100% sure if this have been reported but i did look for any open issues and closed without any luck)

**Comment by TheXFactor117** [comment]
Hmm, you might have a point in that it deletes the inventory. I'll have to do some testing to see if this is the case, though just from thinking about it, I don't see how why it would be doing that. But I'll look just in case.

**Comment by wiloxe** [comment]
We ended up removing the mod untill this issue has been fixed but it would be nice to have a config to disable abilities that you don't want and have a config to make the void ability only work on mobs and not players.

**Comment by TheXFactor117** [comment]
That has been suggested quite a bit. I'm re-writing the mod right now, and will try and implement a blacklist of some sort. I'm also looking into re-working the Void ability as a whole.

**Comment by TheXFactor117** [comment]
Closing this issue for now. The Void ability shouldn't cause inventories to get deleted. If the new version of the mod (which will be released very soon) still causes this problem, open up a new issue.
