### ISSUE TITLE
Configurable Weapon/Armour List

### ISSUE THREAD

**Issue by Funwayguy** [TheXFactor117/Levels#47]
Can we have a config to add/remove leveling support for various weapons or armour? Not only would this be very useful for pack developers to blacklisting already overpowered items, from a mod development point of view it's kinda annoying when you HAVE to extend off of a sword or axes for weapons to be supported by Levels despite there being few reasons for it needing to be either.

**Comment by TheXFactor117** [comment]
This is a very good idea. I'm re-writing the mod right now and will try to incorporate this in the new version. Thanks for the suggestion!
