### ISSUE TITLE
[Crash] Ticking Tinkers Arrows

### ISSUE THREAD

**Issue by Dragnier** [TheXFactor117/Levels#49]
Levels appears to be the cause:

https://gist.github.com/Dragnier/6c82c53378fecdd665e71bec20db5fb4

at com.thexfactor117.levels.leveling.AbilitySelection.getRandomizedAbilities(AbilitySelection.java:38)

https://github.com/SlimeKnights/TinkersConstruct/issues/2694

**Comment by TheXFactor117** [comment]
Thanks. I'm re-writing the mod right now, so I unfortunately won't be able to get a build out with a fix, though I will fix this with the new version of the mod. Sorry for any inconveniences!

**Comment by TheXFactor117** [comment]
If this has any correlation to do with #48 this problem could be potentially fixed.

Keep a look out for the new beta releasing shortly. If the issue persists, open up a new issue with new information.
