### ISSUE TITLE
Enable and Disable Commands not working...

### ISSUE THREAD

**Issue by Boolyman** [TheXFactor117/Levels#64]
Well, its not working because there is no documentation on how to actually use the feature?  What are the commands, or where can we find the commands to force rarities, abilities, and experience as noted in the config file?  

I love the mod, but the lack of up-to-date documentation available for pack devs is a bit discouraging.

**Comment by TheXFactor117** [comment]
Which version are you using? The original Levels or Levels 2?

**Comment by Boolyman** [comment]
Levels 4.1.3 for 1.10.2

**Comment by TheXFactor117** [comment]
[There is a Levels 2 version for 1.10.2](https://minecraft.curseforge.com/projects/levels/files/2369809). Levels 2 doesn't have commands however. The version you are using does. I'm sorry for removing the wiki page on it, I didn't realize I did when I re-worked the wiki. I will be adding in commands in the next version most likely sometime, so if you want to update and wait a couple days, it should all be worked out.

As for the other issue, I'll create another issue about that.
