### ISSUE TITLE
Upgrade page shows max level is 7 ignoring of config

### ISSUE THREAD

**Issue by CplPibald** [TheXFactor117/Levels#76]
If you set config to max level something other than 7, a level 7 weapon still displays as "max".

Problem in [levels/gui/GuiAbilitySelection.java line 190](https://github.com/TheXFactor117/Levels/blob/85dc1cd59edb2cbdecec37558b37e42cfb333646/src/main/java/com/thexfactor117/levels/gui/GuiAbilitySelection.java#L190) 

    if (Experience.getLevel(nbt) == 7)

Should be

    if (Experience.getLevel(nbt) == ConfigHandler.MAX_LEVEL)

**Comment by TheXFactor117** [comment]
Hmm, not too sure how that slipped by. Will be fixed in the next version.

**Comment by CplPibald** [comment]
Thank you for doing this mod, @TheXFactor117.  It is very welcomed.

**Comment by TheXFactor117** [comment]
Of course! Thanks for the reports.

**Comment by TheXFactor117** [comment]
Will be fixed in the next version.
