### ISSUE TITLE
Potentially Utilize Mcjty Compat Layer

### ISSUE THREAD

**Issue by Dragnier** [TheXFactor117/Levels#78]
Compat Layer allows mods to maintain 1.10.2 and 1.11.2 simultaneously. Just don't force require it or embed it. The idea is that a mod is for 1.11 and then IF the player has Compat Layer installed your mod hooks it and then works for 1.10 as well. Most mods are still on 1.10.2 while everything updates.

**Comment by TheXFactor117** [comment]
I'll look into it because updating two versions at the same time is kind of a pain sometimes.

**Comment by TheXFactor117** [comment]
I doubt I will do this. The cost of updating is too much for the benefit. I'd be better off manually porting the mod to 1.10.2 (which I will try to do when I get a chance).
