### ISSUE TITLE
Leveling up armor gives you a message "your weapon has leveled"

### ISSUE THREAD

**Issue by CplPibald** [TheXFactor117/Levels#79]
Leveling up any piece says your **weapon** has leveled even when it is armor.  See [this line](https://github.com/TheXFactor117/Levels/blob/master/src/main/java/com/thexfactor117/levels/leveling/Experience.java#L27) which says weapon no matter what type of item leveled.  

It should choose one of {weapon,helmet,chestplate,leggings,boots} to tell you which piece leveled.

This should probably also use a .lang file entry and not a hardcoded string.

**Comment by TheXFactor117** [comment]
Will be fixed in the next version. Thanks!
