### ISSUE TITLE
bonuses damage-durability not apply ? (Levels 2-1.11.2-b2.2.0)

### ISSUE THREAD

**Issue by Lightone** [TheXFactor117/Levels#82]
that details is missing 

great mod 👍 

![damageother](https://cloud.githubusercontent.com/assets/2113099/22358482/68549c2c-e40d-11e6-9ae1-6becb8983764.png)

**Comment by TheXFactor117** [comment]
What is the issue exactly?

**Comment by Lightone** [comment]
the values of damage and durability no change  with the rarity and levels, look the same only with different color X_x

see lv 1 diamond swords, vs lv 7, the damage and the durability is the same, 

Github Level wiki

> For melee and ranged weapons, rarities provide bonuses to damage, bonus experience, and even durability resistance. This means that the higher the rarity, the weapon will be able to do more damage, receive more experience, and resist more durability

**Comment by TheXFactor117** [comment]
It won't change minecrafts tooltip. Plus, it is only a chance of dealing extra damage. It won't deal it all the time. Durability wise, nothing is wrong with that either.
