### ISSUE TITLE
EnderIO Soulbound enchantment doesn't work with Levels

### ISSUE THREAD

**Issue by frenzye** [TheXFactor117/Levels#85]
If you use the EIO Soulbound enchantment with Levels installed you lose items on death

**Comment by TheXFactor117** [comment]
Added option to remove certain abilities. Should be a workaround for this issue.

**Comment by frenzye** [comment]
what's the workaround?

**Comment by TheXFactor117** [comment]
You can disable the soul bound abilities on weapons and armor now via the config files.

**Comment by frenzye** [comment]
for what it's worth, I put levels back in my modpack, tried with soulbound ability config setting on and off, doesn't work 

Duplicated the pack removing everything except Levels, EnderIO, Ars Magica 2 (also adds a soulbound enchant), and NEI. Soulbound works unless Levels soulbound config is set to false

**Comment by Darkosto** [comment]
Just letting you know, this is still an issue and deletes soulbound items. This currently happening in 3.x and 2.x
