### ISSUE TITLE
Rarity configuration changes not working

### ISSUE THREAD

**Issue by Boolyman** [TheXFactor117/Levels#87]
I set my rarity configuration to this:

rarities {
    S:ancientWeight=0.20
    S:basicWeight=0.0
    S:legendaryWeight=0.30
    S:rareWeight=0.50
    S:uncommonWeight=0.0
}

I did that because those two bottom rarities make a weapon deal less damage than what's listed in the NBT which I don't think is appropriate... especially if the person had to spend rare materials to craft the weapon.  But despite setting both of those rarities at 0% chance to drop, I am still getting both of them.  I even tried them at 5% rarity each, figuring maybe 0% wasn't allowed.  But they were dropping at their default % rate.

Levels version:  Levels 2-1.10.2-b1.1.1
Minecraft version: 1.10.2
Forge:  12.18.3.2202

**Comment by TheXFactor117** [comment]
It isn't fully implemented yet. I will implement it now, when I get a chance. Furthermore, Basic rarities deal as much damage as a normal vanilla weapon will. Others will do more damage. I'll also look into updating the damage that is seen too with rarity bonuses included.

**Comment by TheXFactor117** [comment]
Will be fixed in r1.1.0. This version will be for 1.11.2, though. However, I will also try to back port the 1.11.2 version to 1.10.2 again.

**Comment by Boolyman** [comment]
Should we unclose the ticket since you didn't actually fix it yet?  Helps me keep track of the pending problems with my upcoming modpack release.  But, its your git.

**Comment by TheXFactor117** [comment]
The reason it is closed is because I have fixed it code-wise. I'm making a few general tweaks right now and adding minor features so once I wrap that up, I'll push the build.
