### ISSUE TITLE
Weapons and Armor Not Working Properly

### ISSUE THREAD

**Issue by XenoStone1009** [TheXFactor117/Levels#89]
Recently updated to the latest build and found that I could not deal damage with any sword or axe, and that my armor makes me instantly die from any damage source (I was 1 shotted by a normal skeleton with full health and Resistance 1). It might only be me and a mod conflict doing this (maybe ArmorPlus since i just added along with the updates, further testing needed), but could be due to only this mod (since I disabled it and everything went back to normal).

**Comment by XenoStone1009** [comment]
Readded Levels and Removed ArmorPlus. Still no damaging mobs.

**Comment by TheXFactor117** [comment]
Which Minecraft version?

**Comment by XenoStone1009** [comment]
1.11.2

**Comment by TheXFactor117** [comment]
I've found this issue and fixed it. I wasn't able to reproduce the arrow issue. Perhaps the original issue caused that too. Anyways, I'll release a hotfix in the next 5 minutes. If you don't mind following up on the arrow issue, that would be helpful.

**Comment by XenoStone1009** [comment]
I think that taking any damage from any mob causes my instant death. It just happened to be the skeleton.

**Comment by TheXFactor117** [comment]
I let myself get killed by a skeleton and nothing strange happened. My guess is that armor damage modifiers modified the damage to something weird (negative perhaps?), but when I fixed the weapons it might have fixed armor too.

**Comment by XenoStone1009** [comment]
Heres what I get: https://gyazo.com/1de236e2fe36b9c7f186fb60d2dd2933
Note I have strength 5 and an Iron sword with sharp 1, I should one shot this spider.
As well I have merely a leather helmet but still 1-shotted.

**Comment by TheXFactor117** [comment]
Is this r1.1.0 still?

**Comment by XenoStone1009** [comment]
Yeah, that's 1.1.0
I'm updating now

**Comment by TheXFactor117** [comment]
Update and it should be fixed. Let me know, though.

**Comment by XenoStone1009** [comment]
Yep! Armor and weapons work like normal now!

**Comment by TheXFactor117** [comment]
Awesome!
