### ISSUE TITLE
Server crash on player join

### ISSUE THREAD

**Issue by Practiclycrp** [TheXFactor117/Levels#90]
Levels2-1.11-2-R1.1.1
Forge 1.11.2-13.20.0.2228 (Forge 1.11.2-13.20.0.2226) Tested with both, same issue.
Minecraft 1.11.2

The server crashes upon a player joining after updating to R1.1.1 from R1.0.0. 

Crash Reports;

[crash-2017-02-12_01.49.07-server.txt](https://github.com/TheXFactor117/Levels/files/769133/crash-2017-02-12_01.49.07-server.txt)
[crash-2017-02-12_02.08.55-server.txt](https://github.com/TheXFactor117/Levels/files/769134/crash-2017-02-12_02.08.55-server.txt)
[crash-2017-02-12_01.46.33-server.txt](https://github.com/TheXFactor117/Levels/files/769135/crash-2017-02-12_01.46.33-server.txt)

Mod Config;

[levels.txt](https://github.com/TheXFactor117/Levels/files/769136/levels.txt)

**Comment by TheXFactor117** [comment]
I'm looking into it right now.

**Comment by TheXFactor117** [comment]
Fixed in r1.1.2
