### ISSUE TITLE
New Levels r1.11 broke my level.dat on Forge 13.20.0.2222

### ISSUE THREAD

**Issue by Baalith** [TheXFactor117/Levels#91]
Hi there,

at first I've to say, that I'm a big fan of your mod and it works like a charm in the recent versions.
Now I've updated to the newest version.
After login to MC and starting my survival world I noticed, that:

Hitpoints from enemies are no longer shown in Waila.
And if I get hit by a mob all my hearts go away and my character starts to stutter.
It seems that it is trying to play the death animation, but I stay alive.
Sounds weird.
After MC restart, this behavior stays. Even trying to sleep in a bed doesn't helped.
So I looked into the MC saves folder:
I noticed, that a new level.dat was created and the old one was renamed to level.dat_old.

After a view via NBTExplorer in the level.dat I saw, that the following fields are not definied.

Health: (normally 20) now: n. def.
AbsorptionAmount: n. def.

I resetted those values to 20 and 0 and restarted my survival world.
Same behavior as mentioned above after the first hit by a mob.

So I switched back to levels r1.00 and rolled back a previously made update from my world.

BTW: I have the levelup and the leveluphp mod installed. Both have worked fine together since levelsr1.11

I hope my informations give you a little help to track down this issue.
Best regards

**Comment by TheXFactor117** [comment]
Which version are you using: r1.1.0 or r1.1.1?

**Comment by Baalith** [comment]
The issue was on both versions. So now I switched back to r1.0.0

**Comment by TheXFactor117** [comment]
Hmm...did you update from r1.0.0 to r1.1.0 to begin with, then notice the error? Or was it from r1.0.0 to r1.1.1?

**Comment by Baalith** [comment]
I was updating from r1.0.0 to r1.1.0. Then the issue occurs first.
Later I updated from r1.1.0 to r1.1.1 and the issue stays so I reverted back to r1.0.0

**Comment by TheXFactor117** [comment]
Could you try going from r1.0.0 to r1.1.2?

**Comment by Baalith** [comment]
Okay I updated from r1.0.0 directly to r1.1.2. Everything seems to work fine so far.
I'll report if some issues occur.
Thanks for your great support :)

**Comment by TheXFactor117** [comment]
Awesome
