### ISSUE TITLE
Button Displacement

### ISSUE THREAD

**Issue by Practiclycrp** [TheXFactor117/Levels#96]
In the Levels skill purchasing menu, buttons will be displaced if some abilities are disabled.
![java_2017-02-25_11-05-52](https://cloud.githubusercontent.com/assets/6693462/23333555/84d793b4-fb4a-11e6-8282-609b6c0ae834.png)
In this screenshot I have `B:soulBoundArmorAbility=false` set to false on the server's side, all other abilities are set to true.

Forge 13.20.0.2252
Levels 2 R1.2.0
Minecraft 1.11.2

**Comment by TheXFactor117** [comment]
Hmm...that shouldn't necessarily happen. I'll look into it though.

**Comment by TheXFactor117** [comment]
Fixed in r1.2.1
