### ISSUE TITLE
Crash When Placing Fluid Tank

### ISSUE THREAD

**Issue by Darkosto** [TheXFactor117/Levels#97]
Hello,

It seems there is a crash with the newest update to levels. This particular crash happened when I placed down a tank of Lava from the Mob Grinder Utils mod.

Log: http://pastebin.com/YFu27xJ6

Levels: r1.2.1
MC: 1.10.2
Forge: 2239

Thank you very much!
Darkosto

**Comment by TheXFactor117** [comment]
Try changing the key bindings to something else.

**Comment by Darkosto** [comment]
You mean the keybind to open the levels GUI? It's set to "L" and the button I pressed when the crash happened was the Right Mouse Button.

**Comment by TheXFactor117** [comment]
Should be fixed in r1.2.2.
