### ISSUE TITLE
Crash when hit by mob

### ISSUE THREAD

**Issue by Kashdeya** [TheXFactor117/Levels#99]
Problem: Got hit by a mob and instant crash.

Version: Levels 2-1.10.2-r1.2.2

Forge Version: 12.18.3.2239

Report: http://pastebin.com/uKAM8uMV

More Info: I do not know if it is your mod or the Aqua Creeper mod, but I do know that I did not have this issue until I updated Levels.

**Comment by TheXFactor117** [comment]
Will be fixed in r1.2.3

**Comment by TheXFactor117** [comment]
The build will be released in a couple hours when I get a chance to upload it.
